stages:
  - test
  - build
  - deploy

test:
  image: node:18
  stage: test
  script:
    - npm install
    - npm test

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t todo-api .

deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  script:
    - docker-compose up -d